[[repos]]
url = "https://raw.githubusercontent.com/amanre/amos-leftwm-themes/master/known.toml"
name = "amanre"
definitions_version = 0

[[repos.themes]]
name = "amos-eos-apollo"
repository = "https://github.com/amanre/amos-eos-apollo"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = true

[[repos.themes]]
name = "amos-candy"
repository = "https://github.com/amanre/amos-candy"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = true
